server:
  port: 9090
spring:
  application:
    name: myhrm-gate
  #mysql 数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myhrm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 980727
  #redis
  redis:
    host: localhost
    port: 6379
  cloud:
    #nacos注册中心配置
    nacos:
      server-addr: localhost:8848
    #网关配置
    gateway:
      #路由断言工厂
      routes:
        #系统服务
        - id: myhrm-system
          uri: lb://myhrm-system
          predicates:
            - Path=/sys/**
        #企业服务
        - id: myhrm-company
          uri: lb://myhrm-company
          predicates:
            - Path=/company/**
        #雇员服务
        - id: myhrm-employee
          uri: lb://myhrm-employee
          predicates:
            - Path=/employees/**